// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module initializeBuffer (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        buffer_r_address0,
        buffer_r_ce0,
        buffer_r_we0,
        buffer_r_d0,
        in_data_address0,
        in_data_ce0,
        in_data_q0,
        index_row_out,
        kernel_size_row,
        kernel_size_col
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] buffer_r_address0;
output   buffer_r_ce0;
output   buffer_r_we0;
output  [31:0] buffer_r_d0;
output  [13:0] in_data_address0;
output   in_data_ce0;
input  [31:0] in_data_q0;
input  [30:0] index_row_out;
input  [31:0] kernel_size_row;
input  [31:0] kernel_size_col;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg buffer_r_ce0;
reg buffer_r_we0;
reg in_data_ce0;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] smax_cast_fu_156_p1;
reg   [31:0] smax_cast_reg_254;
wire   [30:0] ik_row_2_fu_169_p2;
reg   [30:0] ik_row_2_reg_262;
wire    ap_CS_fsm_state2;
wire   [31:0] i_buffer_2_fu_175_p2;
reg   [31:0] i_buffer_2_reg_267;
wire   [0:0] tmp_s_fu_164_p2;
wire  signed [14:0] tmp_23_fu_233_p2;
reg  signed [14:0] tmp_23_reg_272;
wire   [30:0] ik_col_2_fu_202_p2;
reg   [30:0] ik_col_2_reg_280;
wire    ap_CS_fsm_state3;
wire   [0:0] tmp_17_fu_197_p2;
wire   [31:0] tmp_19_fu_222_p2;
wire    ap_CS_fsm_state4;
reg   [31:0] i_buffer_reg_93;
reg   [30:0] ik_row_reg_105;
reg  signed [31:0] i_buffer_1_reg_116;
reg   [30:0] ik_col_reg_127;
wire  signed [63:0] tmp_24_cast_fu_217_p1;
wire  signed [63:0] tmp_20_fu_228_p1;
wire   [0:0] tmp_fu_138_p2;
wire   [30:0] tmp_16_fu_144_p1;
wire   [30:0] smax_fu_148_p3;
wire   [31:0] ik_row_cast_fu_160_p1;
wire   [14:0] tmp_25_fu_184_p1;
wire   [14:0] tmp_21_fu_180_p1;
wire   [31:0] ik_col_cast_fu_193_p1;
wire   [14:0] tmp_27_fu_208_p1;
(* use_dsp48 = "no" *) wire   [14:0] tmp_24_fu_212_p2;
wire   [7:0] tmp_23_fu_233_p0;
wire  signed [14:0] tmp_23_fu_233_p1;
reg   [3:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
end

conv2D_mul_mul_8nbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 15 ))
conv2D_mul_mul_8nbkb_U1(
    .din0(tmp_23_fu_233_p0),
    .din1(tmp_23_fu_233_p1),
    .dout(tmp_23_fu_233_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_buffer_1_reg_116 <= tmp_19_fu_222_p2;
    end else if (((tmp_s_fu_164_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i_buffer_1_reg_116 <= i_buffer_reg_93;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_17_fu_197_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        i_buffer_reg_93 <= i_buffer_2_reg_267;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_buffer_reg_93 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ik_col_reg_127 <= ik_col_2_reg_280;
    end else if (((tmp_s_fu_164_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ik_col_reg_127 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_17_fu_197_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        ik_row_reg_105 <= ik_row_2_reg_262;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ik_row_reg_105 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_fu_164_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i_buffer_2_reg_267 <= i_buffer_2_fu_175_p2;
        tmp_23_reg_272 <= tmp_23_fu_233_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ik_col_2_reg_280 <= ik_col_2_fu_202_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ik_row_2_reg_262 <= ik_row_2_fu_169_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        smax_cast_reg_254[30 : 0] <= smax_cast_fu_156_p1[30 : 0];
    end
end

always @ (*) begin
    if ((((tmp_s_fu_164_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_s_fu_164_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_r_ce0 = 1'b1;
    end else begin
        buffer_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_r_we0 = 1'b1;
    end else begin
        buffer_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_data_ce0 = 1'b1;
    end else begin
        in_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_s_fu_164_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((tmp_17_fu_197_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign buffer_r_address0 = tmp_20_fu_228_p1;

assign buffer_r_d0 = in_data_q0;

assign i_buffer_2_fu_175_p2 = (i_buffer_reg_93 + smax_cast_reg_254);

assign ik_col_2_fu_202_p2 = (ik_col_reg_127 + 31'd1);

assign ik_col_cast_fu_193_p1 = ik_col_reg_127;

assign ik_row_2_fu_169_p2 = (ik_row_reg_105 + 31'd1);

assign ik_row_cast_fu_160_p1 = ik_row_reg_105;

assign in_data_address0 = tmp_24_cast_fu_217_p1;

assign smax_cast_fu_156_p1 = smax_fu_148_p3;

assign smax_fu_148_p3 = ((tmp_fu_138_p2[0:0] === 1'b1) ? tmp_16_fu_144_p1 : 31'd0);

assign tmp_16_fu_144_p1 = kernel_size_col[30:0];

assign tmp_17_fu_197_p2 = (($signed(ik_col_cast_fu_193_p1) < $signed(kernel_size_col)) ? 1'b1 : 1'b0);

assign tmp_19_fu_222_p2 = ($signed(32'd1) + $signed(i_buffer_1_reg_116));

assign tmp_20_fu_228_p1 = i_buffer_1_reg_116;

assign tmp_21_fu_180_p1 = ik_row_reg_105[14:0];

assign tmp_23_fu_233_p0 = 15'd100;

assign tmp_23_fu_233_p1 = (tmp_25_fu_184_p1 + tmp_21_fu_180_p1);

assign tmp_24_cast_fu_217_p1 = $signed(tmp_24_fu_212_p2);

assign tmp_24_fu_212_p2 = ($signed(tmp_23_reg_272) + $signed(tmp_27_fu_208_p1));

assign tmp_25_fu_184_p1 = index_row_out[14:0];

assign tmp_27_fu_208_p1 = ik_col_reg_127[14:0];

assign tmp_fu_138_p2 = (($signed(kernel_size_col) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign tmp_s_fu_164_p2 = (($signed(ik_row_cast_fu_160_p1) < $signed(kernel_size_row)) ? 1'b1 : 1'b0);

always @ (posedge ap_clk) begin
    smax_cast_reg_254[31] <= 1'b0;
end

endmodule //initializeBuffer
