// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "conv2D.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic conv2D::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic conv2D::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<7> conv2D::ap_ST_fsm_state1 = "1";
const sc_lv<7> conv2D::ap_ST_fsm_state2 = "10";
const sc_lv<7> conv2D::ap_ST_fsm_state3 = "100";
const sc_lv<7> conv2D::ap_ST_fsm_state4 = "1000";
const sc_lv<7> conv2D::ap_ST_fsm_pp0_stage0 = "10000";
const sc_lv<7> conv2D::ap_ST_fsm_state10 = "100000";
const sc_lv<7> conv2D::ap_ST_fsm_state11 = "1000000";
const sc_lv<32> conv2D::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool conv2D::ap_const_boolean_1 = true;
const sc_lv<32> conv2D::ap_const_lv32_1 = "1";
const sc_lv<1> conv2D::ap_const_lv1_1 = "1";
const sc_lv<32> conv2D::ap_const_lv32_5 = "101";
const sc_lv<32> conv2D::ap_const_lv32_3 = "11";
const sc_lv<32> conv2D::ap_const_lv32_4 = "100";
const bool conv2D::ap_const_boolean_0 = false;
const sc_lv<1> conv2D::ap_const_lv1_0 = "0";
const sc_lv<31> conv2D::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<38> conv2D::ap_const_lv38_0 = "00000000000000000000000000000000000000";
const sc_lv<32> conv2D::ap_const_lv32_2 = "10";
const sc_lv<32> conv2D::ap_const_lv32_6 = "110";
const sc_lv<64> conv2D::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<38> conv2D::ap_const_lv38_64 = "1100100";
const sc_lv<31> conv2D::ap_const_lv31_1 = "1";
const sc_lv<64> conv2D::ap_const_lv64_1 = "1";
const sc_lv<11> conv2D::ap_const_lv11_64 = "1100100";

conv2D::conv2D(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_updateBuffer_fu_307 = new updateBuffer("grp_updateBuffer_fu_307");
    grp_updateBuffer_fu_307->ap_clk(ap_clk);
    grp_updateBuffer_fu_307->ap_rst(ap_rst);
    grp_updateBuffer_fu_307->ap_start(grp_updateBuffer_fu_307_ap_start);
    grp_updateBuffer_fu_307->ap_done(grp_updateBuffer_fu_307_ap_done);
    grp_updateBuffer_fu_307->ap_idle(grp_updateBuffer_fu_307_ap_idle);
    grp_updateBuffer_fu_307->ap_ready(grp_updateBuffer_fu_307_ap_ready);
    grp_updateBuffer_fu_307->buffer_0_read(reg_505);
    grp_updateBuffer_fu_307->buffer_1_read(reg_511);
    grp_updateBuffer_fu_307->buffer_2_read(reg_517);
    grp_updateBuffer_fu_307->buffer_3_read(reg_523);
    grp_updateBuffer_fu_307->buffer_4_read(reg_529);
    grp_updateBuffer_fu_307->buffer_5_read(reg_535);
    grp_updateBuffer_fu_307->buffer_6_read(reg_541);
    grp_updateBuffer_fu_307->buffer_7_read(reg_547);
    grp_updateBuffer_fu_307->buffer_8_read(reg_553);
    grp_updateBuffer_fu_307->buffer_9_read(reg_559);
    grp_updateBuffer_fu_307->buffer_10_read(reg_565);
    grp_updateBuffer_fu_307->buffer_11_read(reg_571);
    grp_updateBuffer_fu_307->buffer_12_read(reg_577);
    grp_updateBuffer_fu_307->buffer_13_read(reg_583);
    grp_updateBuffer_fu_307->buffer_14_read(reg_589);
    grp_updateBuffer_fu_307->buffer_15_read(reg_595);
    grp_updateBuffer_fu_307->buffer_16_read(reg_601);
    grp_updateBuffer_fu_307->buffer_17_read(reg_607);
    grp_updateBuffer_fu_307->buffer_18_read(reg_613);
    grp_updateBuffer_fu_307->buffer_19_read(reg_619);
    grp_updateBuffer_fu_307->buffer_20_read(reg_625);
    grp_updateBuffer_fu_307->buffer_21_read(reg_631);
    grp_updateBuffer_fu_307->buffer_22_read(reg_637);
    grp_updateBuffer_fu_307->buffer_23_read(reg_643);
    grp_updateBuffer_fu_307->buffer_24_read(reg_649);
    grp_updateBuffer_fu_307->in_data_address0(grp_updateBuffer_fu_307_in_data_address0);
    grp_updateBuffer_fu_307->in_data_ce0(grp_updateBuffer_fu_307_in_data_ce0);
    grp_updateBuffer_fu_307->in_data_q0(in_data_q0);
    grp_updateBuffer_fu_307->index_row_out(index_row_out_reg_226);
    grp_updateBuffer_fu_307->index_col_out(index_col_out_reg_249);
    grp_updateBuffer_fu_307->kernel_size_row(kernel_size_row);
    grp_updateBuffer_fu_307->kernel_size_col(kernel_size_col);
    grp_updateBuffer_fu_307->col_in(col_in);
    grp_updateBuffer_fu_307->ap_return_0(grp_updateBuffer_fu_307_ap_return_0);
    grp_updateBuffer_fu_307->ap_return_1(grp_updateBuffer_fu_307_ap_return_1);
    grp_updateBuffer_fu_307->ap_return_2(grp_updateBuffer_fu_307_ap_return_2);
    grp_updateBuffer_fu_307->ap_return_3(grp_updateBuffer_fu_307_ap_return_3);
    grp_updateBuffer_fu_307->ap_return_4(grp_updateBuffer_fu_307_ap_return_4);
    grp_updateBuffer_fu_307->ap_return_5(grp_updateBuffer_fu_307_ap_return_5);
    grp_updateBuffer_fu_307->ap_return_6(grp_updateBuffer_fu_307_ap_return_6);
    grp_updateBuffer_fu_307->ap_return_7(grp_updateBuffer_fu_307_ap_return_7);
    grp_updateBuffer_fu_307->ap_return_8(grp_updateBuffer_fu_307_ap_return_8);
    grp_updateBuffer_fu_307->ap_return_9(grp_updateBuffer_fu_307_ap_return_9);
    grp_updateBuffer_fu_307->ap_return_10(grp_updateBuffer_fu_307_ap_return_10);
    grp_updateBuffer_fu_307->ap_return_11(grp_updateBuffer_fu_307_ap_return_11);
    grp_updateBuffer_fu_307->ap_return_12(grp_updateBuffer_fu_307_ap_return_12);
    grp_updateBuffer_fu_307->ap_return_13(grp_updateBuffer_fu_307_ap_return_13);
    grp_updateBuffer_fu_307->ap_return_14(grp_updateBuffer_fu_307_ap_return_14);
    grp_updateBuffer_fu_307->ap_return_15(grp_updateBuffer_fu_307_ap_return_15);
    grp_updateBuffer_fu_307->ap_return_16(grp_updateBuffer_fu_307_ap_return_16);
    grp_updateBuffer_fu_307->ap_return_17(grp_updateBuffer_fu_307_ap_return_17);
    grp_updateBuffer_fu_307->ap_return_18(grp_updateBuffer_fu_307_ap_return_18);
    grp_updateBuffer_fu_307->ap_return_19(grp_updateBuffer_fu_307_ap_return_19);
    grp_updateBuffer_fu_307->ap_return_20(grp_updateBuffer_fu_307_ap_return_20);
    grp_updateBuffer_fu_307->ap_return_21(grp_updateBuffer_fu_307_ap_return_21);
    grp_updateBuffer_fu_307->ap_return_22(grp_updateBuffer_fu_307_ap_return_22);
    grp_updateBuffer_fu_307->ap_return_23(grp_updateBuffer_fu_307_ap_return_23);
    grp_updateBuffer_fu_307->ap_return_24(grp_updateBuffer_fu_307_ap_return_24);
    grp_initializeBuffer_fu_345 = new initializeBuffer("grp_initializeBuffer_fu_345");
    grp_initializeBuffer_fu_345->ap_clk(ap_clk);
    grp_initializeBuffer_fu_345->ap_rst(ap_rst);
    grp_initializeBuffer_fu_345->ap_start(grp_initializeBuffer_fu_345_ap_start);
    grp_initializeBuffer_fu_345->ap_done(grp_initializeBuffer_fu_345_ap_done);
    grp_initializeBuffer_fu_345->ap_idle(grp_initializeBuffer_fu_345_ap_idle);
    grp_initializeBuffer_fu_345->ap_ready(grp_initializeBuffer_fu_345_ap_ready);
    grp_initializeBuffer_fu_345->buffer_0_read(reg_505);
    grp_initializeBuffer_fu_345->buffer_1_read(reg_511);
    grp_initializeBuffer_fu_345->buffer_2_read(reg_517);
    grp_initializeBuffer_fu_345->buffer_3_read(reg_523);
    grp_initializeBuffer_fu_345->buffer_4_read(reg_529);
    grp_initializeBuffer_fu_345->buffer_5_read(reg_535);
    grp_initializeBuffer_fu_345->buffer_6_read(reg_541);
    grp_initializeBuffer_fu_345->buffer_7_read(reg_547);
    grp_initializeBuffer_fu_345->buffer_8_read(reg_553);
    grp_initializeBuffer_fu_345->buffer_9_read(reg_559);
    grp_initializeBuffer_fu_345->buffer_10_read(reg_565);
    grp_initializeBuffer_fu_345->buffer_11_read(reg_571);
    grp_initializeBuffer_fu_345->buffer_12_read(reg_577);
    grp_initializeBuffer_fu_345->buffer_13_read(reg_583);
    grp_initializeBuffer_fu_345->buffer_14_read(reg_589);
    grp_initializeBuffer_fu_345->buffer_15_read(reg_595);
    grp_initializeBuffer_fu_345->buffer_16_read(reg_601);
    grp_initializeBuffer_fu_345->buffer_17_read(reg_607);
    grp_initializeBuffer_fu_345->buffer_18_read(reg_613);
    grp_initializeBuffer_fu_345->buffer_19_read(reg_619);
    grp_initializeBuffer_fu_345->buffer_20_read(reg_625);
    grp_initializeBuffer_fu_345->buffer_21_read(reg_631);
    grp_initializeBuffer_fu_345->buffer_22_read(reg_637);
    grp_initializeBuffer_fu_345->buffer_23_read(reg_643);
    grp_initializeBuffer_fu_345->buffer_24_read(reg_649);
    grp_initializeBuffer_fu_345->in_data_address0(grp_initializeBuffer_fu_345_in_data_address0);
    grp_initializeBuffer_fu_345->in_data_ce0(grp_initializeBuffer_fu_345_in_data_ce0);
    grp_initializeBuffer_fu_345->in_data_q0(in_data_q0);
    grp_initializeBuffer_fu_345->index_row_out(index_row_out_reg_226);
    grp_initializeBuffer_fu_345->kernel_size_row(kernel_size_row);
    grp_initializeBuffer_fu_345->kernel_size_col(kernel_size_col);
    grp_initializeBuffer_fu_345->ap_return_0(grp_initializeBuffer_fu_345_ap_return_0);
    grp_initializeBuffer_fu_345->ap_return_1(grp_initializeBuffer_fu_345_ap_return_1);
    grp_initializeBuffer_fu_345->ap_return_2(grp_initializeBuffer_fu_345_ap_return_2);
    grp_initializeBuffer_fu_345->ap_return_3(grp_initializeBuffer_fu_345_ap_return_3);
    grp_initializeBuffer_fu_345->ap_return_4(grp_initializeBuffer_fu_345_ap_return_4);
    grp_initializeBuffer_fu_345->ap_return_5(grp_initializeBuffer_fu_345_ap_return_5);
    grp_initializeBuffer_fu_345->ap_return_6(grp_initializeBuffer_fu_345_ap_return_6);
    grp_initializeBuffer_fu_345->ap_return_7(grp_initializeBuffer_fu_345_ap_return_7);
    grp_initializeBuffer_fu_345->ap_return_8(grp_initializeBuffer_fu_345_ap_return_8);
    grp_initializeBuffer_fu_345->ap_return_9(grp_initializeBuffer_fu_345_ap_return_9);
    grp_initializeBuffer_fu_345->ap_return_10(grp_initializeBuffer_fu_345_ap_return_10);
    grp_initializeBuffer_fu_345->ap_return_11(grp_initializeBuffer_fu_345_ap_return_11);
    grp_initializeBuffer_fu_345->ap_return_12(grp_initializeBuffer_fu_345_ap_return_12);
    grp_initializeBuffer_fu_345->ap_return_13(grp_initializeBuffer_fu_345_ap_return_13);
    grp_initializeBuffer_fu_345->ap_return_14(grp_initializeBuffer_fu_345_ap_return_14);
    grp_initializeBuffer_fu_345->ap_return_15(grp_initializeBuffer_fu_345_ap_return_15);
    grp_initializeBuffer_fu_345->ap_return_16(grp_initializeBuffer_fu_345_ap_return_16);
    grp_initializeBuffer_fu_345->ap_return_17(grp_initializeBuffer_fu_345_ap_return_17);
    grp_initializeBuffer_fu_345->ap_return_18(grp_initializeBuffer_fu_345_ap_return_18);
    grp_initializeBuffer_fu_345->ap_return_19(grp_initializeBuffer_fu_345_ap_return_19);
    grp_initializeBuffer_fu_345->ap_return_20(grp_initializeBuffer_fu_345_ap_return_20);
    grp_initializeBuffer_fu_345->ap_return_21(grp_initializeBuffer_fu_345_ap_return_21);
    grp_initializeBuffer_fu_345->ap_return_22(grp_initializeBuffer_fu_345_ap_return_22);
    grp_initializeBuffer_fu_345->ap_return_23(grp_initializeBuffer_fu_345_ap_return_23);
    grp_initializeBuffer_fu_345->ap_return_24(grp_initializeBuffer_fu_345_ap_return_24);
    conv2D_mux_255_32cud_x_U118 = new conv2D_mux_255_32cud_x<1,1,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,5,32>("conv2D_mux_255_32cud_x_U118");
    conv2D_mux_255_32cud_x_U118->din0(buffer_0_fu_76);
    conv2D_mux_255_32cud_x_U118->din1(buffer_1_fu_80);
    conv2D_mux_255_32cud_x_U118->din2(buffer_2_fu_84);
    conv2D_mux_255_32cud_x_U118->din3(buffer_3_fu_88);
    conv2D_mux_255_32cud_x_U118->din4(buffer_4_fu_92);
    conv2D_mux_255_32cud_x_U118->din5(buffer_5_fu_96);
    conv2D_mux_255_32cud_x_U118->din6(buffer_6_fu_100);
    conv2D_mux_255_32cud_x_U118->din7(buffer_7_fu_104);
    conv2D_mux_255_32cud_x_U118->din8(buffer_8_fu_108);
    conv2D_mux_255_32cud_x_U118->din9(buffer_9_fu_112);
    conv2D_mux_255_32cud_x_U118->din10(buffer_10_fu_116);
    conv2D_mux_255_32cud_x_U118->din11(buffer_11_fu_120);
    conv2D_mux_255_32cud_x_U118->din12(buffer_12_fu_124);
    conv2D_mux_255_32cud_x_U118->din13(buffer_13_fu_128);
    conv2D_mux_255_32cud_x_U118->din14(buffer_14_fu_132);
    conv2D_mux_255_32cud_x_U118->din15(buffer_15_fu_136);
    conv2D_mux_255_32cud_x_U118->din16(buffer_16_fu_140);
    conv2D_mux_255_32cud_x_U118->din17(buffer_17_fu_144);
    conv2D_mux_255_32cud_x_U118->din18(buffer_18_fu_148);
    conv2D_mux_255_32cud_x_U118->din19(buffer_19_fu_152);
    conv2D_mux_255_32cud_x_U118->din20(buffer_20_fu_156);
    conv2D_mux_255_32cud_x_U118->din21(buffer_21_fu_160);
    conv2D_mux_255_32cud_x_U118->din22(buffer_22_fu_164);
    conv2D_mux_255_32cud_x_U118->din23(buffer_23_fu_168);
    conv2D_mux_255_32cud_x_U118->din24(buffer_24_fu_172);
    conv2D_mux_255_32cud_x_U118->din25(tmp_29_t_i_reg_1624);
    conv2D_mux_255_32cud_x_U118->dout(tmp_28_fu_1030_p27);
    conv2D_mac_muladdfYi_U119 = new conv2D_mac_muladdfYi<1,1,8,11,11,11>("conv2D_mac_muladdfYi_U119");
    conv2D_mac_muladdfYi_U119->din0(grp_fu_1333_p0);
    conv2D_mac_muladdfYi_U119->din1(tmp_33_reg_1599);
    conv2D_mac_muladdfYi_U119->din2(tmp_36_reg_1614);
    conv2D_mac_muladdfYi_U119->dout(grp_fu_1333_p3);
    conv2D_mac_muladdg8j_U120 = new conv2D_mac_muladdg8j<1,1,5,5,5,5>("conv2D_mac_muladdg8j_U120");
    conv2D_mac_muladdg8j_U120->din0(tmp_34_reg_1604);
    conv2D_mac_muladdg8j_U120->din1(tmp_26_reg_1548);
    conv2D_mac_muladdg8j_U120->din2(tmp_35_reg_1609);
    conv2D_mac_muladdg8j_U120->dout(grp_fu_1340_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter4);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state5);
    sensitive << ( exitcond_flatten_fu_971_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_21_fu_711_p2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_ap_phi_mux_ik_row_i_phi_fu_276_p4);
    sensitive << ( ik_row_i_reg_272 );
    sensitive << ( exitcond_flatten_reg_1585 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( tmp_27_i_mid2_v_reg_1594 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_21_fu_711_p2 );

    SC_METHOD(thread_bound_fu_691_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( bound_fu_691_p00 );

    SC_METHOD(thread_bound_fu_691_p00);
    sensitive << ( kernel_size_col );

    SC_METHOD(thread_bound_fu_691_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( bound_fu_691_p10 );

    SC_METHOD(thread_bound_fu_691_p10);
    sensitive << ( kernel_size_row );

    SC_METHOD(thread_bound_fu_691_p2);
    sensitive << ( bound_fu_691_p0 );
    sensitive << ( bound_fu_691_p1 );

    SC_METHOD(thread_exitcond_flatten_fu_971_p2);
    sensitive << ( indvar_flatten_reg_261 );
    sensitive << ( bound_reg_1553 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_grp_fu_1333_p0);
    sensitive << ( exitcond_flatten_reg_1585 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_initializeBuffer_fu_345_ap_start);
    sensitive << ( grp_initializeBuffer_fu_345_ap_start_reg );

    SC_METHOD(thread_grp_updateBuffer_fu_307_ap_start);
    sensitive << ( grp_updateBuffer_fu_307_ap_start_reg );

    SC_METHOD(thread_ik_col_fu_1020_p2);
    sensitive << ( ik_col_i_mid2_fu_988_p3 );

    SC_METHOD(thread_ik_col_i_cast_fu_962_p1);
    sensitive << ( ik_col_i_reg_296 );

    SC_METHOD(thread_ik_col_i_mid2_fu_988_p3);
    sensitive << ( ik_col_i_reg_296 );
    sensitive << ( tmp_28_i_fu_966_p2 );

    SC_METHOD(thread_ik_row_fu_982_p2);
    sensitive << ( ap_phi_mux_ik_row_i_phi_fu_276_p4 );

    SC_METHOD(thread_in_data_address0);
    sensitive << ( grp_updateBuffer_fu_307_in_data_address0 );
    sensitive << ( grp_initializeBuffer_fu_345_in_data_address0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_in_data_ce0);
    sensitive << ( grp_updateBuffer_fu_307_in_data_ce0 );
    sensitive << ( grp_initializeBuffer_fu_345_in_data_ce0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_index_col_out_1_fu_956_p2);
    sensitive << ( index_col_out_reg_249 );

    SC_METHOD(thread_index_col_out_cast_fu_947_p1);
    sensitive << ( index_col_out_reg_249 );

    SC_METHOD(thread_index_row_out_1_fu_716_p2);
    sensitive << ( index_row_out_reg_226 );

    SC_METHOD(thread_index_row_out_cast_fu_707_p1);
    sensitive << ( index_row_out_reg_226 );

    SC_METHOD(thread_indvar_flatten_next_fu_976_p2);
    sensitive << ( indvar_flatten_reg_261 );

    SC_METHOD(thread_kernel_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_31_cast_fu_1026_p1 );

    SC_METHOD(thread_kernel_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_next_mul_fu_701_p2);
    sensitive << ( phi_mul_reg_238 );

    SC_METHOD(thread_out_data_address0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_29_cast_fu_1103_p1 );

    SC_METHOD(thread_out_data_ce0);
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_out_data_d0);
    sensitive << ( sum_1_i_reg_283 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_out_data_we0);
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_sum_fu_1089_p2);
    sensitive << ( sum_1_i_reg_283 );
    sensitive << ( tmp_32_i_reg_1644 );

    SC_METHOD(thread_tmp_19_fu_667_p2);
    sensitive << ( col_in );

    SC_METHOD(thread_tmp_20_fu_673_p2);
    sensitive << ( kernel_size_col );
    sensitive << ( tmp_19_fu_667_p2 );

    SC_METHOD(thread_tmp_21_fu_711_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_s_reg_1538 );
    sensitive << ( index_row_out_cast_fu_707_p1 );

    SC_METHOD(thread_tmp_23_fu_951_p2);
    sensitive << ( tmp_20_reg_1543 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( index_col_out_cast_fu_947_p1 );

    SC_METHOD(thread_tmp_25_fu_1098_p2);
    sensitive << ( tmp_27_reg_1558 );
    sensitive << ( tmp_32_fu_1094_p1 );

    SC_METHOD(thread_tmp_26_fu_679_p1);
    sensitive << ( kernel_size_col );

    SC_METHOD(thread_tmp_27_fu_697_p1);
    sensitive << ( phi_mul_reg_238 );

    SC_METHOD(thread_tmp_27_i_mid2_v_fu_996_p3);
    sensitive << ( ap_phi_mux_ik_row_i_phi_fu_276_p4 );
    sensitive << ( tmp_28_i_fu_966_p2 );
    sensitive << ( ik_row_fu_982_p2 );

    SC_METHOD(thread_tmp_28_i_fu_966_p2);
    sensitive << ( kernel_size_col );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ik_col_i_cast_fu_962_p1 );

    SC_METHOD(thread_tmp_29_cast_fu_1103_p1);
    sensitive << ( tmp_25_fu_1098_p2 );

    SC_METHOD(thread_tmp_31_cast_fu_1026_p1);
    sensitive << ( grp_fu_1333_p3 );

    SC_METHOD(thread_tmp_32_fu_1094_p1);
    sensitive << ( index_col_out_reg_249 );

    SC_METHOD(thread_tmp_32_i_fu_1085_p2);
    sensitive << ( tmp_28_reg_1634 );
    sensitive << ( kernel_load_reg_1639 );

    SC_METHOD(thread_tmp_33_fu_1004_p1);
    sensitive << ( tmp_27_i_mid2_v_fu_996_p3 );

    SC_METHOD(thread_tmp_34_fu_1008_p1);
    sensitive << ( tmp_27_i_mid2_v_fu_996_p3 );

    SC_METHOD(thread_tmp_35_fu_1012_p1);
    sensitive << ( ik_col_i_mid2_fu_988_p3 );

    SC_METHOD(thread_tmp_36_fu_1016_p1);
    sensitive << ( ik_col_i_mid2_fu_988_p3 );

    SC_METHOD(thread_tmp_fu_655_p2);
    sensitive << ( row_in );

    SC_METHOD(thread_tmp_s_fu_661_p2);
    sensitive << ( kernel_size_row );
    sensitive << ( tmp_fu_655_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_21_fu_711_p2 );
    sensitive << ( tmp_23_fu_951_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond_flatten_fu_971_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( grp_updateBuffer_fu_307_ap_done );
    sensitive << ( grp_initializeBuffer_fu_345_ap_done );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "0000001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    grp_updateBuffer_fu_307_ap_start_reg = SC_LOGIC_0;
    grp_initializeBuffer_fu_345_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "conv2D_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_data_address0, "(port)in_data_address0");
    sc_trace(mVcdFile, in_data_ce0, "(port)in_data_ce0");
    sc_trace(mVcdFile, in_data_q0, "(port)in_data_q0");
    sc_trace(mVcdFile, out_data_address0, "(port)out_data_address0");
    sc_trace(mVcdFile, out_data_ce0, "(port)out_data_ce0");
    sc_trace(mVcdFile, out_data_we0, "(port)out_data_we0");
    sc_trace(mVcdFile, out_data_d0, "(port)out_data_d0");
    sc_trace(mVcdFile, row_in, "(port)row_in");
    sc_trace(mVcdFile, col_in, "(port)col_in");
    sc_trace(mVcdFile, kernel_address0, "(port)kernel_address0");
    sc_trace(mVcdFile, kernel_ce0, "(port)kernel_ce0");
    sc_trace(mVcdFile, kernel_q0, "(port)kernel_q0");
    sc_trace(mVcdFile, kernel_size_row, "(port)kernel_size_row");
    sc_trace(mVcdFile, kernel_size_col, "(port)kernel_size_col");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, indvar_flatten_reg_261, "indvar_flatten_reg_261");
    sc_trace(mVcdFile, ik_row_i_reg_272, "ik_row_i_reg_272");
    sc_trace(mVcdFile, sum_1_i_reg_283, "sum_1_i_reg_283");
    sc_trace(mVcdFile, ik_col_i_reg_296, "ik_col_i_reg_296");
    sc_trace(mVcdFile, reg_505, "reg_505");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_21_fu_711_p2, "tmp_21_fu_711_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, reg_511, "reg_511");
    sc_trace(mVcdFile, reg_517, "reg_517");
    sc_trace(mVcdFile, reg_523, "reg_523");
    sc_trace(mVcdFile, reg_529, "reg_529");
    sc_trace(mVcdFile, reg_535, "reg_535");
    sc_trace(mVcdFile, reg_541, "reg_541");
    sc_trace(mVcdFile, reg_547, "reg_547");
    sc_trace(mVcdFile, reg_553, "reg_553");
    sc_trace(mVcdFile, reg_559, "reg_559");
    sc_trace(mVcdFile, reg_565, "reg_565");
    sc_trace(mVcdFile, reg_571, "reg_571");
    sc_trace(mVcdFile, reg_577, "reg_577");
    sc_trace(mVcdFile, reg_583, "reg_583");
    sc_trace(mVcdFile, reg_589, "reg_589");
    sc_trace(mVcdFile, reg_595, "reg_595");
    sc_trace(mVcdFile, reg_601, "reg_601");
    sc_trace(mVcdFile, reg_607, "reg_607");
    sc_trace(mVcdFile, reg_613, "reg_613");
    sc_trace(mVcdFile, reg_619, "reg_619");
    sc_trace(mVcdFile, reg_625, "reg_625");
    sc_trace(mVcdFile, reg_631, "reg_631");
    sc_trace(mVcdFile, reg_637, "reg_637");
    sc_trace(mVcdFile, reg_643, "reg_643");
    sc_trace(mVcdFile, reg_649, "reg_649");
    sc_trace(mVcdFile, tmp_s_fu_661_p2, "tmp_s_fu_661_p2");
    sc_trace(mVcdFile, tmp_s_reg_1538, "tmp_s_reg_1538");
    sc_trace(mVcdFile, tmp_20_fu_673_p2, "tmp_20_fu_673_p2");
    sc_trace(mVcdFile, tmp_20_reg_1543, "tmp_20_reg_1543");
    sc_trace(mVcdFile, tmp_26_fu_679_p1, "tmp_26_fu_679_p1");
    sc_trace(mVcdFile, tmp_26_reg_1548, "tmp_26_reg_1548");
    sc_trace(mVcdFile, bound_fu_691_p2, "bound_fu_691_p2");
    sc_trace(mVcdFile, bound_reg_1553, "bound_reg_1553");
    sc_trace(mVcdFile, tmp_27_fu_697_p1, "tmp_27_fu_697_p1");
    sc_trace(mVcdFile, tmp_27_reg_1558, "tmp_27_reg_1558");
    sc_trace(mVcdFile, next_mul_fu_701_p2, "next_mul_fu_701_p2");
    sc_trace(mVcdFile, next_mul_reg_1563, "next_mul_reg_1563");
    sc_trace(mVcdFile, index_row_out_1_fu_716_p2, "index_row_out_1_fu_716_p2");
    sc_trace(mVcdFile, index_row_out_1_reg_1571, "index_row_out_1_reg_1571");
    sc_trace(mVcdFile, tmp_23_fu_951_p2, "tmp_23_fu_951_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, index_col_out_1_fu_956_p2, "index_col_out_1_fu_956_p2");
    sc_trace(mVcdFile, index_col_out_1_reg_1580, "index_col_out_1_reg_1580");
    sc_trace(mVcdFile, exitcond_flatten_fu_971_p2, "exitcond_flatten_fu_971_p2");
    sc_trace(mVcdFile, exitcond_flatten_reg_1585, "exitcond_flatten_reg_1585");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter0, "ap_block_state5_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter1, "ap_block_state6_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter2, "ap_block_state7_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter3, "ap_block_state8_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter4, "ap_block_state9_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, exitcond_flatten_reg_1585_pp0_iter1_reg, "exitcond_flatten_reg_1585_pp0_iter1_reg");
    sc_trace(mVcdFile, exitcond_flatten_reg_1585_pp0_iter2_reg, "exitcond_flatten_reg_1585_pp0_iter2_reg");
    sc_trace(mVcdFile, exitcond_flatten_reg_1585_pp0_iter3_reg, "exitcond_flatten_reg_1585_pp0_iter3_reg");
    sc_trace(mVcdFile, indvar_flatten_next_fu_976_p2, "indvar_flatten_next_fu_976_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_27_i_mid2_v_fu_996_p3, "tmp_27_i_mid2_v_fu_996_p3");
    sc_trace(mVcdFile, tmp_27_i_mid2_v_reg_1594, "tmp_27_i_mid2_v_reg_1594");
    sc_trace(mVcdFile, tmp_33_fu_1004_p1, "tmp_33_fu_1004_p1");
    sc_trace(mVcdFile, tmp_33_reg_1599, "tmp_33_reg_1599");
    sc_trace(mVcdFile, tmp_34_fu_1008_p1, "tmp_34_fu_1008_p1");
    sc_trace(mVcdFile, tmp_34_reg_1604, "tmp_34_reg_1604");
    sc_trace(mVcdFile, tmp_35_fu_1012_p1, "tmp_35_fu_1012_p1");
    sc_trace(mVcdFile, tmp_35_reg_1609, "tmp_35_reg_1609");
    sc_trace(mVcdFile, tmp_36_fu_1016_p1, "tmp_36_fu_1016_p1");
    sc_trace(mVcdFile, tmp_36_reg_1614, "tmp_36_reg_1614");
    sc_trace(mVcdFile, ik_col_fu_1020_p2, "ik_col_fu_1020_p2");
    sc_trace(mVcdFile, grp_fu_1340_p3, "grp_fu_1340_p3");
    sc_trace(mVcdFile, tmp_29_t_i_reg_1624, "tmp_29_t_i_reg_1624");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, tmp_28_fu_1030_p27, "tmp_28_fu_1030_p27");
    sc_trace(mVcdFile, tmp_28_reg_1634, "tmp_28_reg_1634");
    sc_trace(mVcdFile, kernel_load_reg_1639, "kernel_load_reg_1639");
    sc_trace(mVcdFile, tmp_32_i_fu_1085_p2, "tmp_32_i_fu_1085_p2");
    sc_trace(mVcdFile, tmp_32_i_reg_1644, "tmp_32_i_reg_1644");
    sc_trace(mVcdFile, sum_fu_1089_p2, "sum_fu_1089_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state5, "ap_condition_pp0_exit_iter0_state5");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_start, "grp_updateBuffer_fu_307_ap_start");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_done, "grp_updateBuffer_fu_307_ap_done");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_idle, "grp_updateBuffer_fu_307_ap_idle");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_ready, "grp_updateBuffer_fu_307_ap_ready");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_in_data_address0, "grp_updateBuffer_fu_307_in_data_address0");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_in_data_ce0, "grp_updateBuffer_fu_307_in_data_ce0");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_0, "grp_updateBuffer_fu_307_ap_return_0");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_1, "grp_updateBuffer_fu_307_ap_return_1");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_2, "grp_updateBuffer_fu_307_ap_return_2");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_3, "grp_updateBuffer_fu_307_ap_return_3");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_4, "grp_updateBuffer_fu_307_ap_return_4");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_5, "grp_updateBuffer_fu_307_ap_return_5");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_6, "grp_updateBuffer_fu_307_ap_return_6");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_7, "grp_updateBuffer_fu_307_ap_return_7");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_8, "grp_updateBuffer_fu_307_ap_return_8");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_9, "grp_updateBuffer_fu_307_ap_return_9");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_10, "grp_updateBuffer_fu_307_ap_return_10");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_11, "grp_updateBuffer_fu_307_ap_return_11");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_12, "grp_updateBuffer_fu_307_ap_return_12");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_13, "grp_updateBuffer_fu_307_ap_return_13");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_14, "grp_updateBuffer_fu_307_ap_return_14");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_15, "grp_updateBuffer_fu_307_ap_return_15");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_16, "grp_updateBuffer_fu_307_ap_return_16");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_17, "grp_updateBuffer_fu_307_ap_return_17");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_18, "grp_updateBuffer_fu_307_ap_return_18");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_19, "grp_updateBuffer_fu_307_ap_return_19");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_20, "grp_updateBuffer_fu_307_ap_return_20");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_21, "grp_updateBuffer_fu_307_ap_return_21");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_22, "grp_updateBuffer_fu_307_ap_return_22");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_23, "grp_updateBuffer_fu_307_ap_return_23");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_return_24, "grp_updateBuffer_fu_307_ap_return_24");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_start, "grp_initializeBuffer_fu_345_ap_start");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_done, "grp_initializeBuffer_fu_345_ap_done");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_idle, "grp_initializeBuffer_fu_345_ap_idle");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_ready, "grp_initializeBuffer_fu_345_ap_ready");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_in_data_address0, "grp_initializeBuffer_fu_345_in_data_address0");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_in_data_ce0, "grp_initializeBuffer_fu_345_in_data_ce0");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_0, "grp_initializeBuffer_fu_345_ap_return_0");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_1, "grp_initializeBuffer_fu_345_ap_return_1");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_2, "grp_initializeBuffer_fu_345_ap_return_2");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_3, "grp_initializeBuffer_fu_345_ap_return_3");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_4, "grp_initializeBuffer_fu_345_ap_return_4");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_5, "grp_initializeBuffer_fu_345_ap_return_5");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_6, "grp_initializeBuffer_fu_345_ap_return_6");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_7, "grp_initializeBuffer_fu_345_ap_return_7");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_8, "grp_initializeBuffer_fu_345_ap_return_8");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_9, "grp_initializeBuffer_fu_345_ap_return_9");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_10, "grp_initializeBuffer_fu_345_ap_return_10");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_11, "grp_initializeBuffer_fu_345_ap_return_11");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_12, "grp_initializeBuffer_fu_345_ap_return_12");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_13, "grp_initializeBuffer_fu_345_ap_return_13");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_14, "grp_initializeBuffer_fu_345_ap_return_14");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_15, "grp_initializeBuffer_fu_345_ap_return_15");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_16, "grp_initializeBuffer_fu_345_ap_return_16");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_17, "grp_initializeBuffer_fu_345_ap_return_17");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_18, "grp_initializeBuffer_fu_345_ap_return_18");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_19, "grp_initializeBuffer_fu_345_ap_return_19");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_20, "grp_initializeBuffer_fu_345_ap_return_20");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_21, "grp_initializeBuffer_fu_345_ap_return_21");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_22, "grp_initializeBuffer_fu_345_ap_return_22");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_23, "grp_initializeBuffer_fu_345_ap_return_23");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_return_24, "grp_initializeBuffer_fu_345_ap_return_24");
    sc_trace(mVcdFile, index_row_out_reg_226, "index_row_out_reg_226");
    sc_trace(mVcdFile, phi_mul_reg_238, "phi_mul_reg_238");
    sc_trace(mVcdFile, index_col_out_reg_249, "index_col_out_reg_249");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_phi_mux_ik_row_i_phi_fu_276_p4, "ap_phi_mux_ik_row_i_phi_fu_276_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, grp_updateBuffer_fu_307_ap_start_reg, "grp_updateBuffer_fu_307_ap_start_reg");
    sc_trace(mVcdFile, grp_initializeBuffer_fu_345_ap_start_reg, "grp_initializeBuffer_fu_345_ap_start_reg");
    sc_trace(mVcdFile, tmp_31_cast_fu_1026_p1, "tmp_31_cast_fu_1026_p1");
    sc_trace(mVcdFile, tmp_29_cast_fu_1103_p1, "tmp_29_cast_fu_1103_p1");
    sc_trace(mVcdFile, buffer_0_fu_76, "buffer_0_fu_76");
    sc_trace(mVcdFile, buffer_1_fu_80, "buffer_1_fu_80");
    sc_trace(mVcdFile, buffer_2_fu_84, "buffer_2_fu_84");
    sc_trace(mVcdFile, buffer_3_fu_88, "buffer_3_fu_88");
    sc_trace(mVcdFile, buffer_4_fu_92, "buffer_4_fu_92");
    sc_trace(mVcdFile, buffer_5_fu_96, "buffer_5_fu_96");
    sc_trace(mVcdFile, buffer_6_fu_100, "buffer_6_fu_100");
    sc_trace(mVcdFile, buffer_7_fu_104, "buffer_7_fu_104");
    sc_trace(mVcdFile, buffer_8_fu_108, "buffer_8_fu_108");
    sc_trace(mVcdFile, buffer_9_fu_112, "buffer_9_fu_112");
    sc_trace(mVcdFile, buffer_10_fu_116, "buffer_10_fu_116");
    sc_trace(mVcdFile, buffer_11_fu_120, "buffer_11_fu_120");
    sc_trace(mVcdFile, buffer_12_fu_124, "buffer_12_fu_124");
    sc_trace(mVcdFile, buffer_13_fu_128, "buffer_13_fu_128");
    sc_trace(mVcdFile, buffer_14_fu_132, "buffer_14_fu_132");
    sc_trace(mVcdFile, buffer_15_fu_136, "buffer_15_fu_136");
    sc_trace(mVcdFile, buffer_16_fu_140, "buffer_16_fu_140");
    sc_trace(mVcdFile, buffer_17_fu_144, "buffer_17_fu_144");
    sc_trace(mVcdFile, buffer_18_fu_148, "buffer_18_fu_148");
    sc_trace(mVcdFile, buffer_19_fu_152, "buffer_19_fu_152");
    sc_trace(mVcdFile, buffer_20_fu_156, "buffer_20_fu_156");
    sc_trace(mVcdFile, buffer_21_fu_160, "buffer_21_fu_160");
    sc_trace(mVcdFile, buffer_22_fu_164, "buffer_22_fu_164");
    sc_trace(mVcdFile, buffer_23_fu_168, "buffer_23_fu_168");
    sc_trace(mVcdFile, buffer_24_fu_172, "buffer_24_fu_172");
    sc_trace(mVcdFile, tmp_fu_655_p2, "tmp_fu_655_p2");
    sc_trace(mVcdFile, tmp_19_fu_667_p2, "tmp_19_fu_667_p2");
    sc_trace(mVcdFile, bound_fu_691_p0, "bound_fu_691_p0");
    sc_trace(mVcdFile, bound_fu_691_p1, "bound_fu_691_p1");
    sc_trace(mVcdFile, index_row_out_cast_fu_707_p1, "index_row_out_cast_fu_707_p1");
    sc_trace(mVcdFile, index_col_out_cast_fu_947_p1, "index_col_out_cast_fu_947_p1");
    sc_trace(mVcdFile, ik_col_i_cast_fu_962_p1, "ik_col_i_cast_fu_962_p1");
    sc_trace(mVcdFile, tmp_28_i_fu_966_p2, "tmp_28_i_fu_966_p2");
    sc_trace(mVcdFile, ik_row_fu_982_p2, "ik_row_fu_982_p2");
    sc_trace(mVcdFile, ik_col_i_mid2_fu_988_p3, "ik_col_i_mid2_fu_988_p3");
    sc_trace(mVcdFile, grp_fu_1333_p3, "grp_fu_1333_p3");
    sc_trace(mVcdFile, tmp_32_fu_1094_p1, "tmp_32_fu_1094_p1");
    sc_trace(mVcdFile, tmp_25_fu_1098_p2, "tmp_25_fu_1098_p2");
    sc_trace(mVcdFile, grp_fu_1333_p0, "grp_fu_1333_p0");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, bound_fu_691_p00, "bound_fu_691_p00");
    sc_trace(mVcdFile, bound_fu_691_p10, "bound_fu_691_p10");
#endif

    }
    mHdltvinHandle.open("conv2D.hdltvin.dat");
    mHdltvoutHandle.open("conv2D.hdltvout.dat");
}

conv2D::~conv2D() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete grp_updateBuffer_fu_307;
    delete grp_initializeBuffer_fu_345;
    delete conv2D_mux_255_32cud_x_U118;
    delete conv2D_mac_muladdfYi_U119;
    delete conv2D_mac_muladdg8j_U120;
}

void conv2D::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state5.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, tmp_23_fu_951_p2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state5.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state5.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, tmp_23_fu_951_p2.read()))) {
            ap_enable_reg_pp0_iter4 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_0_fu_76 = grp_updateBuffer_fu_307_ap_return_0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_0_fu_76 = grp_initializeBuffer_fu_345_ap_return_0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_10_fu_116 = grp_updateBuffer_fu_307_ap_return_10.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_10_fu_116 = grp_initializeBuffer_fu_345_ap_return_10.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_11_fu_120 = grp_updateBuffer_fu_307_ap_return_11.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_11_fu_120 = grp_initializeBuffer_fu_345_ap_return_11.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_12_fu_124 = grp_updateBuffer_fu_307_ap_return_12.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_12_fu_124 = grp_initializeBuffer_fu_345_ap_return_12.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_13_fu_128 = grp_updateBuffer_fu_307_ap_return_13.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_13_fu_128 = grp_initializeBuffer_fu_345_ap_return_13.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_14_fu_132 = grp_updateBuffer_fu_307_ap_return_14.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_14_fu_132 = grp_initializeBuffer_fu_345_ap_return_14.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_15_fu_136 = grp_updateBuffer_fu_307_ap_return_15.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_15_fu_136 = grp_initializeBuffer_fu_345_ap_return_15.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_16_fu_140 = grp_updateBuffer_fu_307_ap_return_16.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_16_fu_140 = grp_initializeBuffer_fu_345_ap_return_16.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_17_fu_144 = grp_updateBuffer_fu_307_ap_return_17.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_17_fu_144 = grp_initializeBuffer_fu_345_ap_return_17.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_18_fu_148 = grp_updateBuffer_fu_307_ap_return_18.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_18_fu_148 = grp_initializeBuffer_fu_345_ap_return_18.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_19_fu_152 = grp_updateBuffer_fu_307_ap_return_19.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_19_fu_152 = grp_initializeBuffer_fu_345_ap_return_19.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_1_fu_80 = grp_updateBuffer_fu_307_ap_return_1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_1_fu_80 = grp_initializeBuffer_fu_345_ap_return_1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_20_fu_156 = grp_updateBuffer_fu_307_ap_return_20.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_20_fu_156 = grp_initializeBuffer_fu_345_ap_return_20.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_21_fu_160 = grp_updateBuffer_fu_307_ap_return_21.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_21_fu_160 = grp_initializeBuffer_fu_345_ap_return_21.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_22_fu_164 = grp_updateBuffer_fu_307_ap_return_22.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_22_fu_164 = grp_initializeBuffer_fu_345_ap_return_22.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_23_fu_168 = grp_updateBuffer_fu_307_ap_return_23.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_23_fu_168 = grp_initializeBuffer_fu_345_ap_return_23.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_24_fu_172 = grp_updateBuffer_fu_307_ap_return_24.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_24_fu_172 = grp_initializeBuffer_fu_345_ap_return_24.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_2_fu_84 = grp_updateBuffer_fu_307_ap_return_2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_2_fu_84 = grp_initializeBuffer_fu_345_ap_return_2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_3_fu_88 = grp_updateBuffer_fu_307_ap_return_3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_3_fu_88 = grp_initializeBuffer_fu_345_ap_return_3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_4_fu_92 = grp_updateBuffer_fu_307_ap_return_4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_4_fu_92 = grp_initializeBuffer_fu_345_ap_return_4.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_5_fu_96 = grp_updateBuffer_fu_307_ap_return_5.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_5_fu_96 = grp_initializeBuffer_fu_345_ap_return_5.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_6_fu_100 = grp_updateBuffer_fu_307_ap_return_6.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_6_fu_100 = grp_initializeBuffer_fu_345_ap_return_6.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_7_fu_104 = grp_updateBuffer_fu_307_ap_return_7.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_7_fu_104 = grp_initializeBuffer_fu_345_ap_return_7.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_8_fu_108 = grp_updateBuffer_fu_307_ap_return_8.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_8_fu_108 = grp_initializeBuffer_fu_345_ap_return_8.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        buffer_9_fu_112 = grp_updateBuffer_fu_307_ap_return_9.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        buffer_9_fu_112 = grp_initializeBuffer_fu_345_ap_return_9.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_initializeBuffer_fu_345_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
             esl_seteq<1,1,1>(tmp_21_fu_711_p2.read(), ap_const_lv1_1))) {
            grp_initializeBuffer_fu_345_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_initializeBuffer_fu_345_ap_ready.read())) {
            grp_initializeBuffer_fu_345_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_updateBuffer_fu_307_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
            grp_updateBuffer_fu_307_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_updateBuffer_fu_307_ap_ready.read())) {
            grp_updateBuffer_fu_307_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_fu_971_p2.read(), ap_const_lv1_0))) {
        ik_col_i_reg_296 = ik_col_fu_1020_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_23_fu_951_p2.read()))) {
        ik_col_i_reg_296 = ap_const_lv31_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_1585.read(), ap_const_lv1_0))) {
        ik_row_i_reg_272 = tmp_27_i_mid2_v_reg_1594.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_23_fu_951_p2.read()))) {
        ik_row_i_reg_272 = ap_const_lv31_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
        index_col_out_reg_249 = index_col_out_1_reg_1580.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
        index_col_out_reg_249 = ap_const_lv31_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(tmp_23_fu_951_p2.read(), ap_const_lv1_0))) {
        index_row_out_reg_226 = index_row_out_1_reg_1571.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        index_row_out_reg_226 = ap_const_lv31_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_fu_971_p2.read(), ap_const_lv1_0))) {
        indvar_flatten_reg_261 = indvar_flatten_next_fu_976_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_23_fu_951_p2.read()))) {
        indvar_flatten_reg_261 = ap_const_lv64_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(tmp_23_fu_951_p2.read(), ap_const_lv1_0))) {
        phi_mul_reg_238 = next_mul_reg_1563.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        phi_mul_reg_238 = ap_const_lv38_0;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_1585_pp0_iter3_reg.read(), ap_const_lv1_0))) {
        sum_1_i_reg_283 = sum_fu_1089_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_23_fu_951_p2.read()))) {
        sum_1_i_reg_283 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        bound_reg_1553 = bound_fu_691_p2.read();
        tmp_20_reg_1543 = tmp_20_fu_673_p2.read();
        tmp_26_reg_1548 = tmp_26_fu_679_p1.read();
        tmp_s_reg_1538 = tmp_s_fu_661_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond_flatten_reg_1585 = exitcond_flatten_fu_971_p2.read();
        exitcond_flatten_reg_1585_pp0_iter1_reg = exitcond_flatten_reg_1585.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        exitcond_flatten_reg_1585_pp0_iter2_reg = exitcond_flatten_reg_1585_pp0_iter1_reg.read();
        exitcond_flatten_reg_1585_pp0_iter3_reg = exitcond_flatten_reg_1585_pp0_iter2_reg.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        index_col_out_1_reg_1580 = index_col_out_1_fu_956_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        index_row_out_1_reg_1571 = index_row_out_1_fu_716_p2.read();
        next_mul_reg_1563 = next_mul_fu_701_p2.read();
        tmp_27_reg_1558 = tmp_27_fu_697_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_reg_1585_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        kernel_load_reg_1639 = kernel_q0.read();
        tmp_28_reg_1634 = tmp_28_fu_1030_p27.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
  esl_seteq<1,1,1>(tmp_21_fu_711_p2.read(), ap_const_lv1_1)) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        reg_505 = buffer_0_fu_76.read();
        reg_511 = buffer_1_fu_80.read();
        reg_517 = buffer_2_fu_84.read();
        reg_523 = buffer_3_fu_88.read();
        reg_529 = buffer_4_fu_92.read();
        reg_535 = buffer_5_fu_96.read();
        reg_541 = buffer_6_fu_100.read();
        reg_547 = buffer_7_fu_104.read();
        reg_553 = buffer_8_fu_108.read();
        reg_559 = buffer_9_fu_112.read();
        reg_565 = buffer_10_fu_116.read();
        reg_571 = buffer_11_fu_120.read();
        reg_577 = buffer_12_fu_124.read();
        reg_583 = buffer_13_fu_128.read();
        reg_589 = buffer_14_fu_132.read();
        reg_595 = buffer_15_fu_136.read();
        reg_601 = buffer_16_fu_140.read();
        reg_607 = buffer_17_fu_144.read();
        reg_613 = buffer_18_fu_148.read();
        reg_619 = buffer_19_fu_152.read();
        reg_625 = buffer_20_fu_156.read();
        reg_631 = buffer_21_fu_160.read();
        reg_637 = buffer_22_fu_164.read();
        reg_643 = buffer_23_fu_168.read();
        reg_649 = buffer_24_fu_172.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(exitcond_flatten_fu_971_p2.read(), ap_const_lv1_0))) {
        tmp_27_i_mid2_v_reg_1594 = tmp_27_i_mid2_v_fu_996_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(exitcond_flatten_reg_1585.read(), ap_const_lv1_0))) {
        tmp_29_t_i_reg_1624 = grp_fu_1340_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_reg_1585_pp0_iter2_reg.read(), ap_const_lv1_0))) {
        tmp_32_i_reg_1644 = tmp_32_i_fu_1085_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_fu_971_p2.read(), ap_const_lv1_0))) {
        tmp_33_reg_1599 = tmp_33_fu_1004_p1.read();
        tmp_34_reg_1604 = tmp_34_fu_1008_p1.read();
        tmp_35_reg_1609 = tmp_35_fu_1012_p1.read();
        tmp_36_reg_1614 = tmp_36_fu_1016_p1.read();
    }
}

void conv2D::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[4];
}

void conv2D::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void conv2D::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[5];
}

void conv2D::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[6];
}

void conv2D::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void conv2D::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void conv2D::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void conv2D::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D::thread_ap_block_state5_pp0_stage0_iter0() {
    ap_block_state5_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D::thread_ap_block_state6_pp0_stage0_iter1() {
    ap_block_state6_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D::thread_ap_block_state7_pp0_stage0_iter2() {
    ap_block_state7_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D::thread_ap_block_state8_pp0_stage0_iter3() {
    ap_block_state8_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D::thread_ap_block_state9_pp0_stage0_iter4() {
    ap_block_state9_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D::thread_ap_condition_pp0_exit_iter0_state5() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_flatten_fu_971_p2.read())) {
        ap_condition_pp0_exit_iter0_state5 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state5 = ap_const_logic_0;
    }
}

void conv2D::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_21_fu_711_p2.read(), ap_const_lv1_0))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void conv2D::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void conv2D::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void conv2D::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void conv2D::thread_ap_phi_mux_ik_row_i_phi_fu_276_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_1585.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_ik_row_i_phi_fu_276_p4 = tmp_27_i_mid2_v_reg_1594.read();
    } else {
        ap_phi_mux_ik_row_i_phi_fu_276_p4 = ik_row_i_reg_272.read();
    }
}

void conv2D::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_21_fu_711_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void conv2D::thread_bound_fu_691_p0() {
    bound_fu_691_p0 =  (sc_lv<32>) (bound_fu_691_p00.read());
}

void conv2D::thread_bound_fu_691_p00() {
    bound_fu_691_p00 = esl_zext<64,32>(kernel_size_col.read());
}

void conv2D::thread_bound_fu_691_p1() {
    bound_fu_691_p1 =  (sc_lv<32>) (bound_fu_691_p10.read());
}

void conv2D::thread_bound_fu_691_p10() {
    bound_fu_691_p10 = esl_zext<64,32>(kernel_size_row.read());
}

void conv2D::thread_bound_fu_691_p2() {
    bound_fu_691_p2 = (!bound_fu_691_p0.read().is_01() || !bound_fu_691_p1.read().is_01())? sc_lv<64>(): sc_biguint<32>(bound_fu_691_p0.read()) * sc_biguint<32>(bound_fu_691_p1.read());
}

void conv2D::thread_exitcond_flatten_fu_971_p2() {
    exitcond_flatten_fu_971_p2 = (!indvar_flatten_reg_261.read().is_01() || !bound_reg_1553.read().is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_261.read() == bound_reg_1553.read());
}

void conv2D::thread_grp_fu_1333_p0() {
    grp_fu_1333_p0 =  (sc_lv<8>) (ap_const_lv11_64);
}

void conv2D::thread_grp_initializeBuffer_fu_345_ap_start() {
    grp_initializeBuffer_fu_345_ap_start = grp_initializeBuffer_fu_345_ap_start_reg.read();
}

void conv2D::thread_grp_updateBuffer_fu_307_ap_start() {
    grp_updateBuffer_fu_307_ap_start = grp_updateBuffer_fu_307_ap_start_reg.read();
}

void conv2D::thread_ik_col_fu_1020_p2() {
    ik_col_fu_1020_p2 = (!ap_const_lv31_1.is_01() || !ik_col_i_mid2_fu_988_p3.read().is_01())? sc_lv<31>(): (sc_biguint<31>(ap_const_lv31_1) + sc_biguint<31>(ik_col_i_mid2_fu_988_p3.read()));
}

void conv2D::thread_ik_col_i_cast_fu_962_p1() {
    ik_col_i_cast_fu_962_p1 = esl_zext<32,31>(ik_col_i_reg_296.read());
}

void conv2D::thread_ik_col_i_mid2_fu_988_p3() {
    ik_col_i_mid2_fu_988_p3 = (!tmp_28_i_fu_966_p2.read()[0].is_01())? sc_lv<31>(): ((tmp_28_i_fu_966_p2.read()[0].to_bool())? ik_col_i_reg_296.read(): ap_const_lv31_0);
}

void conv2D::thread_ik_row_fu_982_p2() {
    ik_row_fu_982_p2 = (!ap_const_lv31_1.is_01() || !ap_phi_mux_ik_row_i_phi_fu_276_p4.read().is_01())? sc_lv<31>(): (sc_biguint<31>(ap_const_lv31_1) + sc_biguint<31>(ap_phi_mux_ik_row_i_phi_fu_276_p4.read()));
}

void conv2D::thread_in_data_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in_data_address0 = grp_initializeBuffer_fu_345_in_data_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        in_data_address0 = grp_updateBuffer_fu_307_in_data_address0.read();
    } else {
        in_data_address0 = "XXXXXXXXXXXXXX";
    }
}

void conv2D::thread_in_data_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in_data_ce0 = grp_initializeBuffer_fu_345_in_data_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        in_data_ce0 = grp_updateBuffer_fu_307_in_data_ce0.read();
    } else {
        in_data_ce0 = ap_const_logic_0;
    }
}

void conv2D::thread_index_col_out_1_fu_956_p2() {
    index_col_out_1_fu_956_p2 = (!index_col_out_reg_249.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(index_col_out_reg_249.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void conv2D::thread_index_col_out_cast_fu_947_p1() {
    index_col_out_cast_fu_947_p1 = esl_zext<32,31>(index_col_out_reg_249.read());
}

void conv2D::thread_index_row_out_1_fu_716_p2() {
    index_row_out_1_fu_716_p2 = (!ap_const_lv31_1.is_01() || !index_row_out_reg_226.read().is_01())? sc_lv<31>(): (sc_biguint<31>(ap_const_lv31_1) + sc_biguint<31>(index_row_out_reg_226.read()));
}

void conv2D::thread_index_row_out_cast_fu_707_p1() {
    index_row_out_cast_fu_707_p1 = esl_zext<32,31>(index_row_out_reg_226.read());
}

void conv2D::thread_indvar_flatten_next_fu_976_p2() {
    indvar_flatten_next_fu_976_p2 = (!indvar_flatten_reg_261.read().is_01() || !ap_const_lv64_1.is_01())? sc_lv<64>(): (sc_biguint<64>(indvar_flatten_reg_261.read()) + sc_biguint<64>(ap_const_lv64_1));
}

void conv2D::thread_kernel_address0() {
    kernel_address0 =  (sc_lv<10>) (tmp_31_cast_fu_1026_p1.read());
}

void conv2D::thread_kernel_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        kernel_ce0 = ap_const_logic_1;
    } else {
        kernel_ce0 = ap_const_logic_0;
    }
}

void conv2D::thread_next_mul_fu_701_p2() {
    next_mul_fu_701_p2 = (!ap_const_lv38_64.is_01() || !phi_mul_reg_238.read().is_01())? sc_lv<38>(): (sc_biguint<38>(ap_const_lv38_64) + sc_biguint<38>(phi_mul_reg_238.read()));
}

void conv2D::thread_out_data_address0() {
    out_data_address0 =  (sc_lv<14>) (tmp_29_cast_fu_1103_p1.read());
}

void conv2D::thread_out_data_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        out_data_ce0 = ap_const_logic_1;
    } else {
        out_data_ce0 = ap_const_logic_0;
    }
}

void conv2D::thread_out_data_d0() {
    out_data_d0 = sum_1_i_reg_283.read();
}

void conv2D::thread_out_data_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        out_data_we0 = ap_const_logic_1;
    } else {
        out_data_we0 = ap_const_logic_0;
    }
}

void conv2D::thread_sum_fu_1089_p2() {
    sum_fu_1089_p2 = (!tmp_32_i_reg_1644.read().is_01() || !sum_1_i_reg_283.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_32_i_reg_1644.read()) + sc_biguint<32>(sum_1_i_reg_283.read()));
}

void conv2D::thread_tmp_19_fu_667_p2() {
    tmp_19_fu_667_p2 = (!ap_const_lv32_1.is_01() || !col_in.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(col_in.read()));
}

void conv2D::thread_tmp_20_fu_673_p2() {
    tmp_20_fu_673_p2 = (!tmp_19_fu_667_p2.read().is_01() || !kernel_size_col.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_19_fu_667_p2.read()) - sc_biguint<32>(kernel_size_col.read()));
}

void conv2D::thread_tmp_21_fu_711_p2() {
    tmp_21_fu_711_p2 = (!index_row_out_cast_fu_707_p1.read().is_01() || !tmp_s_reg_1538.read().is_01())? sc_lv<1>(): (sc_bigint<32>(index_row_out_cast_fu_707_p1.read()) < sc_bigint<32>(tmp_s_reg_1538.read()));
}

void conv2D::thread_tmp_23_fu_951_p2() {
    tmp_23_fu_951_p2 = (!index_col_out_cast_fu_947_p1.read().is_01() || !tmp_20_reg_1543.read().is_01())? sc_lv<1>(): (sc_bigint<32>(index_col_out_cast_fu_947_p1.read()) < sc_bigint<32>(tmp_20_reg_1543.read()));
}

void conv2D::thread_tmp_25_fu_1098_p2() {
    tmp_25_fu_1098_p2 = (!tmp_27_reg_1558.read().is_01() || !tmp_32_fu_1094_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_27_reg_1558.read()) + sc_biguint<15>(tmp_32_fu_1094_p1.read()));
}

void conv2D::thread_tmp_26_fu_679_p1() {
    tmp_26_fu_679_p1 = kernel_size_col.read().range(5-1, 0);
}

void conv2D::thread_tmp_27_fu_697_p1() {
    tmp_27_fu_697_p1 = phi_mul_reg_238.read().range(15-1, 0);
}

void conv2D::thread_tmp_27_i_mid2_v_fu_996_p3() {
    tmp_27_i_mid2_v_fu_996_p3 = (!tmp_28_i_fu_966_p2.read()[0].is_01())? sc_lv<31>(): ((tmp_28_i_fu_966_p2.read()[0].to_bool())? ap_phi_mux_ik_row_i_phi_fu_276_p4.read(): ik_row_fu_982_p2.read());
}

void conv2D::thread_tmp_28_i_fu_966_p2() {
    tmp_28_i_fu_966_p2 = (!ik_col_i_cast_fu_962_p1.read().is_01() || !kernel_size_col.read().is_01())? sc_lv<1>(): (sc_bigint<32>(ik_col_i_cast_fu_962_p1.read()) < sc_bigint<32>(kernel_size_col.read()));
}

void conv2D::thread_tmp_29_cast_fu_1103_p1() {
    tmp_29_cast_fu_1103_p1 = esl_zext<64,15>(tmp_25_fu_1098_p2.read());
}

void conv2D::thread_tmp_31_cast_fu_1026_p1() {
    tmp_31_cast_fu_1026_p1 = esl_sext<64,11>(grp_fu_1333_p3.read());
}

void conv2D::thread_tmp_32_fu_1094_p1() {
    tmp_32_fu_1094_p1 = index_col_out_reg_249.read().range(15-1, 0);
}

void conv2D::thread_tmp_32_i_fu_1085_p2() {
    tmp_32_i_fu_1085_p2 = (!kernel_load_reg_1639.read().is_01() || !tmp_28_reg_1634.read().is_01())? sc_lv<32>(): sc_bigint<32>(kernel_load_reg_1639.read()) * sc_bigint<32>(tmp_28_reg_1634.read());
}

void conv2D::thread_tmp_33_fu_1004_p1() {
    tmp_33_fu_1004_p1 = tmp_27_i_mid2_v_fu_996_p3.read().range(11-1, 0);
}

void conv2D::thread_tmp_34_fu_1008_p1() {
    tmp_34_fu_1008_p1 = tmp_27_i_mid2_v_fu_996_p3.read().range(5-1, 0);
}

void conv2D::thread_tmp_35_fu_1012_p1() {
    tmp_35_fu_1012_p1 = ik_col_i_mid2_fu_988_p3.read().range(5-1, 0);
}

void conv2D::thread_tmp_36_fu_1016_p1() {
    tmp_36_fu_1016_p1 = ik_col_i_mid2_fu_988_p3.read().range(11-1, 0);
}

void conv2D::thread_tmp_fu_655_p2() {
    tmp_fu_655_p2 = (!ap_const_lv32_1.is_01() || !row_in.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(row_in.read()));
}

void conv2D::thread_tmp_s_fu_661_p2() {
    tmp_s_fu_661_p2 = (!tmp_fu_655_p2.read().is_01() || !kernel_size_row.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_fu_655_p2.read()) - sc_biguint<32>(kernel_size_row.read()));
}

void conv2D::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_21_fu_711_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(grp_initializeBuffer_fu_345_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(tmp_23_fu_951_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 16 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_flatten_fu_971_p2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_flatten_fu_971_p2.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(grp_updateBuffer_fu_307_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<7>) ("XXXXXXX");
            break;
    }
}

void conv2D::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_data_address0\" :  \"" << in_data_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_data_ce0\" :  \"" << in_data_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_data_q0\" :  \"" << in_data_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_data_address0\" :  \"" << out_data_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_data_ce0\" :  \"" << out_data_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_data_we0\" :  \"" << out_data_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_data_d0\" :  \"" << out_data_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"row_in\" :  \"" << row_in.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"col_in\" :  \"" << col_in.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"kernel_address0\" :  \"" << kernel_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"kernel_ce0\" :  \"" << kernel_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"kernel_q0\" :  \"" << kernel_q0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"kernel_size_row\" :  \"" << kernel_size_row.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"kernel_size_col\" :  \"" << kernel_size_col.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

