// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Loop_Output_Row_proc_HH_
#define _Loop_Output_Row_proc_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "updateBuffer.h"
#include "conv2D_mul_mul_8ndEe.h"
#include "Loop_Output_Row_pcud.h"

namespace ap_rtl {

struct Loop_Output_Row_proc : public sc_module {
    // Port declarations 21
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > row_in;
    sc_in< sc_lv<32> > kernel_size_row;
    sc_in< sc_lv<32> > col_in;
    sc_in< sc_lv<32> > kernel_size_col;
    sc_out< sc_lv<14> > in_data_address0;
    sc_out< sc_logic > in_data_ce0;
    sc_in< sc_lv<32> > in_data_q0;
    sc_out< sc_lv<10> > kernel_address0;
    sc_out< sc_logic > kernel_ce0;
    sc_in< sc_lv<32> > kernel_q0;
    sc_out< sc_lv<14> > out_data_address0;
    sc_out< sc_logic > out_data_ce0;
    sc_out< sc_logic > out_data_we0;
    sc_out< sc_lv<32> > out_data_d0;


    // Module declarations
    Loop_Output_Row_proc(sc_module_name name);
    SC_HAS_PROCESS(Loop_Output_Row_proc);

    ~Loop_Output_Row_proc();

    sc_trace_file* mVcdFile;

    Loop_Output_Row_pcud* buffer_U;
    updateBuffer* grp_updateBuffer_fu_303;
    conv2D_mul_mul_8ndEe<1,1,8,15,15>* conv2D_mul_mul_8ndEe_U10;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<12> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<32> > tmp_s_fu_323_p2;
    sc_signal< sc_lv<32> > tmp_s_reg_596;
    sc_signal< sc_lv<32> > tmp_17_fu_335_p2;
    sc_signal< sc_lv<32> > tmp_17_reg_601;
    sc_signal< sc_lv<32> > smax_cast_i_fu_359_p1;
    sc_signal< sc_lv<32> > smax_cast_i_reg_606;
    sc_signal< sc_lv<15> > tmp_23_fu_363_p1;
    sc_signal< sc_lv<15> > tmp_23_reg_611;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<38> > next_mul4_fu_367_p2;
    sc_signal< sc_lv<38> > next_mul4_reg_616;
    sc_signal< sc_lv<31> > index_row_out_fu_382_p2;
    sc_signal< sc_lv<31> > index_row_out_reg_624;
    sc_signal< sc_lv<31> > ik_row_fu_397_p2;
    sc_signal< sc_lv<31> > ik_row_reg_632;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<32> > i_buffer_fu_403_p2;
    sc_signal< sc_lv<32> > i_buffer_reg_637;
    sc_signal< sc_lv<1> > tmp_i_4_fu_392_p2;
    sc_signal< sc_lv<15> > tmp_24_fu_570_p2;
    sc_signal< sc_lv<15> > tmp_24_reg_642;
    sc_signal< sc_lv<31> > ik_col_fu_431_p2;
    sc_signal< sc_lv<31> > ik_col_reg_650;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > tmp_17_i_fu_426_p2;
    sc_signal< sc_lv<32> > tmp_19_i_fu_451_p2;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<31> > index_col_out_1_fu_471_p2;
    sc_signal< sc_lv<31> > index_col_out_1_reg_668;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<11> > tmp_32_fu_477_p1;
    sc_signal< sc_lv<11> > tmp_32_reg_673;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<38> > next_mul2_fu_481_p2;
    sc_signal< sc_lv<38> > next_mul2_reg_678;
    sc_signal< sc_lv<32> > next_mul_fu_487_p2;
    sc_signal< sc_lv<32> > next_mul_reg_683;
    sc_signal< sc_lv<31> > ik_row_2_fu_501_p2;
    sc_signal< sc_lv<31> > ik_row_2_reg_691;
    sc_signal< sc_lv<31> > ik_col_2_fu_530_p2;
    sc_signal< sc_lv<31> > ik_col_2_reg_699;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<1> > tmp_25_i_fu_525_p2;
    sc_signal< sc_lv<32> > buffer_q0;
    sc_signal< sc_lv<32> > buffer_load_reg_714;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<32> > kernel_load_reg_719;
    sc_signal< sc_lv<32> > tmp_30_i_fu_561_p2;
    sc_signal< sc_lv<32> > tmp_30_i_reg_724;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<32> > sum_1_fu_565_p2;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<5> > buffer_address0;
    sc_signal< sc_logic > buffer_ce0;
    sc_signal< sc_logic > buffer_we0;
    sc_signal< sc_lv<32> > buffer_d0;
    sc_signal< sc_logic > grp_updateBuffer_fu_303_ap_start;
    sc_signal< sc_logic > grp_updateBuffer_fu_303_ap_done;
    sc_signal< sc_logic > grp_updateBuffer_fu_303_ap_idle;
    sc_signal< sc_logic > grp_updateBuffer_fu_303_ap_ready;
    sc_signal< sc_lv<5> > grp_updateBuffer_fu_303_buffer_r_address0;
    sc_signal< sc_logic > grp_updateBuffer_fu_303_buffer_r_ce0;
    sc_signal< sc_logic > grp_updateBuffer_fu_303_buffer_r_we0;
    sc_signal< sc_lv<32> > grp_updateBuffer_fu_303_buffer_r_d0;
    sc_signal< sc_lv<14> > grp_updateBuffer_fu_303_in_data_address0;
    sc_signal< sc_logic > grp_updateBuffer_fu_303_in_data_ce0;
    sc_signal< sc_lv<31> > index_row_out_assign_reg_153;
    sc_signal< sc_lv<1> > tmp_21_fu_466_p2;
    sc_signal< sc_lv<38> > phi_mul3_reg_165;
    sc_signal< sc_lv<32> > i_buffer_i_reg_176;
    sc_signal< sc_lv<1> > tmp_18_fu_377_p2;
    sc_signal< sc_lv<31> > ik_row_i_reg_188;
    sc_signal< sc_lv<32> > i_buffer_1_i_reg_199;
    sc_signal< sc_lv<31> > ik_col_i_reg_210;
    sc_signal< sc_lv<31> > index_col_out_reg_221;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<32> > sum_reg_233;
    sc_signal< sc_lv<31> > ik_row_i1_reg_246;
    sc_signal< sc_lv<32> > phi_mul_reg_257;
    sc_signal< sc_lv<38> > phi_mul1_reg_269;
    sc_signal< sc_lv<32> > sum_1_i_reg_280;
    sc_signal< sc_lv<1> > tmp_i3_fu_496_p2;
    sc_signal< sc_lv<31> > ik_col_i5_reg_292;
    sc_signal< sc_logic > grp_updateBuffer_fu_303_ap_start_reg;
    sc_signal< sc_lv<64> > tmp_26_cast_fu_446_p1;
    sc_signal< sc_lv<64> > tmp_20_i_fu_457_p1;
    sc_signal< sc_lv<64> > tmp_28_cast_fu_516_p1;
    sc_signal< sc_lv<64> > tmp_28_i_fu_542_p1;
    sc_signal< sc_lv<64> > tmp_29_cast_fu_556_p1;
    sc_signal< sc_lv<32> > tmp_fu_317_p2;
    sc_signal< sc_lv<32> > tmp_16_fu_329_p2;
    sc_signal< sc_lv<1> > tmp_i_fu_341_p2;
    sc_signal< sc_lv<31> > tmp_20_fu_347_p1;
    sc_signal< sc_lv<31> > smax_i_fu_351_p3;
    sc_signal< sc_lv<32> > index_row_out_cast_fu_373_p1;
    sc_signal< sc_lv<32> > ik_row_cast_i_fu_388_p1;
    sc_signal< sc_lv<15> > tmp_27_fu_412_p1;
    sc_signal< sc_lv<15> > tmp_25_fu_408_p1;
    sc_signal< sc_lv<32> > ik_col_cast_i_fu_422_p1;
    sc_signal< sc_lv<15> > tmp_31_fu_437_p1;
    sc_signal< sc_lv<15> > tmp_26_fu_441_p2;
    sc_signal< sc_lv<32> > index_col_out_cast_fu_462_p1;
    sc_signal< sc_lv<32> > ik_row_cast_i2_fu_492_p1;
    sc_signal< sc_lv<15> > tmp_33_fu_507_p1;
    sc_signal< sc_lv<15> > tmp_28_fu_511_p2;
    sc_signal< sc_lv<32> > ik_col_cast_i6_fu_521_p1;
    sc_signal< sc_lv<32> > tmp_27_i_fu_536_p2;
    sc_signal< sc_lv<11> > tmp_34_fu_547_p1;
    sc_signal< sc_lv<11> > tmp_29_fu_551_p2;
    sc_signal< sc_lv<8> > tmp_24_fu_570_p0;
    sc_signal< sc_lv<15> > tmp_24_fu_570_p1;
    sc_signal< sc_lv<12> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<12> ap_ST_fsm_state1;
    static const sc_lv<12> ap_ST_fsm_state2;
    static const sc_lv<12> ap_ST_fsm_state3;
    static const sc_lv<12> ap_ST_fsm_state4;
    static const sc_lv<12> ap_ST_fsm_state5;
    static const sc_lv<12> ap_ST_fsm_state6;
    static const sc_lv<12> ap_ST_fsm_state7;
    static const sc_lv<12> ap_ST_fsm_state8;
    static const sc_lv<12> ap_ST_fsm_state9;
    static const sc_lv<12> ap_ST_fsm_state10;
    static const sc_lv<12> ap_ST_fsm_state11;
    static const sc_lv<12> ap_ST_fsm_state12;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<31> ap_const_lv31_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<38> ap_const_lv38_0;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<38> ap_const_lv38_64;
    static const sc_lv<31> ap_const_lv31_1;
    static const sc_lv<15> ap_const_lv15_64;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_block_state1();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_buffer_address0();
    void thread_buffer_ce0();
    void thread_buffer_d0();
    void thread_buffer_we0();
    void thread_grp_updateBuffer_fu_303_ap_start();
    void thread_i_buffer_fu_403_p2();
    void thread_ik_col_2_fu_530_p2();
    void thread_ik_col_cast_i6_fu_521_p1();
    void thread_ik_col_cast_i_fu_422_p1();
    void thread_ik_col_fu_431_p2();
    void thread_ik_row_2_fu_501_p2();
    void thread_ik_row_cast_i2_fu_492_p1();
    void thread_ik_row_cast_i_fu_388_p1();
    void thread_ik_row_fu_397_p2();
    void thread_in_data_address0();
    void thread_in_data_ce0();
    void thread_index_col_out_1_fu_471_p2();
    void thread_index_col_out_cast_fu_462_p1();
    void thread_index_row_out_cast_fu_373_p1();
    void thread_index_row_out_fu_382_p2();
    void thread_kernel_address0();
    void thread_kernel_ce0();
    void thread_next_mul2_fu_481_p2();
    void thread_next_mul4_fu_367_p2();
    void thread_next_mul_fu_487_p2();
    void thread_out_data_address0();
    void thread_out_data_ce0();
    void thread_out_data_d0();
    void thread_out_data_we0();
    void thread_smax_cast_i_fu_359_p1();
    void thread_smax_i_fu_351_p3();
    void thread_sum_1_fu_565_p2();
    void thread_tmp_16_fu_329_p2();
    void thread_tmp_17_fu_335_p2();
    void thread_tmp_17_i_fu_426_p2();
    void thread_tmp_18_fu_377_p2();
    void thread_tmp_19_i_fu_451_p2();
    void thread_tmp_20_fu_347_p1();
    void thread_tmp_20_i_fu_457_p1();
    void thread_tmp_21_fu_466_p2();
    void thread_tmp_23_fu_363_p1();
    void thread_tmp_24_fu_570_p0();
    void thread_tmp_24_fu_570_p1();
    void thread_tmp_25_fu_408_p1();
    void thread_tmp_25_i_fu_525_p2();
    void thread_tmp_26_cast_fu_446_p1();
    void thread_tmp_26_fu_441_p2();
    void thread_tmp_27_fu_412_p1();
    void thread_tmp_27_i_fu_536_p2();
    void thread_tmp_28_cast_fu_516_p1();
    void thread_tmp_28_fu_511_p2();
    void thread_tmp_28_i_fu_542_p1();
    void thread_tmp_29_cast_fu_556_p1();
    void thread_tmp_29_fu_551_p2();
    void thread_tmp_30_i_fu_561_p2();
    void thread_tmp_31_fu_437_p1();
    void thread_tmp_32_fu_477_p1();
    void thread_tmp_33_fu_507_p1();
    void thread_tmp_34_fu_547_p1();
    void thread_tmp_fu_317_p2();
    void thread_tmp_i3_fu_496_p2();
    void thread_tmp_i_4_fu_392_p2();
    void thread_tmp_i_fu_341_p2();
    void thread_tmp_s_fu_323_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
